load("@rules_java//java:defs.bzl", "java_binary")

java_binary(
    name = "p1",
    srcs = glob(["p1/src/com/hydra/wsb/Pracownik.java"]),
    main_class = "sem3.java.wyklad.w02.p1.src.com.hydra.wsb.Pracownik",
)
